var CANVAS_WIDTH = 1920;
var CANVAS_HEIGHT = 1920;

var EDGEBOARD_X = 200;
var EDGEBOARD_Y = 200;

var FONT = "MontserratSemiBold";


var FPS      = 30;
var DISABLE_SOUND_MOBILE = false;

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var NUM_ROWS = 3;
var NUM_COLS = 3;
var CHARACTER_NUM = 4;
var BIGGER_HEIGHT = 267;
var START_X_GRID = 650;
var START_Y_GRID = 830;


var TIME_X = 530;
var TIME_Y = 590;
var SCORE_X = 1160;
var SCORE_Y = 590;
var BEST_SCORE_X = 945;
var BEST_SCORE_Y = 590;
var HOLE_WIDTH = 297;
var HOLE_HEIGHT = 253;
var HAMMER_WIDTH = 258;
var HAMMER_HEIGHT = 225;
var TIME_LEVEL;
var SUPER_HAMMER_MULT;
var SUPER_HAMMER_TIME;


var CHARACTER_WIDTH = new Array();
    CHARACTER_WIDTH[0] = 192;
    CHARACTER_WIDTH[1] = 192;
    CHARACTER_WIDTH[2] = 192;
    CHARACTER_WIDTH[3] = 212;
    CHARACTER_WIDTH[4] = 212;


var CHARACTER_HEIGHT = new Array();
    CHARACTER_HEIGHT[0] = 170;    
    CHARACTER_HEIGHT[1] = 170;
    CHARACTER_HEIGHT[2] = 170;
    CHARACTER_HEIGHT[3] = 191;
    CHARACTER_HEIGHT[4] = 191;
    
    
var CHARACTER_POINTS = new Array();
var GAME_1_POINT = [10, 20, 30, -100]

var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_DRAG_START  = 4;
var ON_DRAG_END    = 5;
var ON_BUT_YES_DOWN = 6;

var START_SPAWN_TIME;
var TIME_OFFSET_PER_SPAWN_DECREASE;
var OFFSET_SPAWN_TIME;
var TIME_SUPER_HAMMER_CHECK;
                                                
var ENABLE_FULLSCREEN;